### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by dirn** [PyGotham/pygotham#109]
SSL is one honking great idea -- let's do more of it.

**Comment by jonafato** [comment]
We're already approved for GlobalSign's [open source initiative](https://www.globalsign.com/en/ssl/ssl-open-source/)[0], and [Let's Encrypt](https://letsencrypt.org/) launches in mid-2015. We'll probably end up going with GlobalSign because of the timing of Let's Encrypt's launch.

[0] This is awesome, glad to see that they're supporting the open source community!
