### ISSUE TITLE
Have twitter tweet buttons next to talks on schedule page. 

### ISSUE THREAD

**Issue by logston** [PyGotham/pygotham#128]

**Comment by jonafato** [comment]
Relevant docs: https://dev.twitter.com/web/tweet-button

**Comment by crazcalm** [comment]
Is there any ideas of what type of twitter button we want? (https://about.twitter.com/resources/buttons) There are 4 types and the link allows you to preview them. Thoughts?

**Comment by dirn** [comment]
I believe we want the Tweet one, but what the canned message should be, I have no idea.

**Comment by jmeekr** [comment]
To be clear, this issue is so that there are multiple tweet buttons, one next to every talk?  Which will populate a tweet about that current talk a user can share?  i.e., @user #pygotham Python For People, Room #101, 12:00 Saturday.

Or one button that grabs the talk from some kind of select, such as radio.

The latter method could be useful for other types of automatic notification, but we'd still be populating a large number of elements on the page which might be messy.

**Comment by jonafato** [comment]
@jmeekr I think this is a per-talk button, but @logston filed the issue and would be the best person to clarify here.

**Comment by dirn** [comment]
I imagine it's a button on the talk detail page. But ¯\_(ツ)_/¯

**Comment by logston** [comment]
>  this issue is so that there are multiple tweet buttons, one next to every talk

yes

> Which will populate a tweet about that current talk a user can share? 

Don't know. didn't get that far in the spec. I'd say default to tweeing the speaker and title and `#pygotham`.

**Comment by dirn** [comment]
I'm closing this issue until it's been updated to contain a spec.
