### ISSUE TITLE
Add Twitter handle to user profile

### ISSUE THREAD

**Issue by dirn** [PyGotham/pygotham#148]
A new field called `twitter_handle` should be added to the `User` model. It should be editable through the `profile.settings` endpoint and the admin (`UserModelView`).

**Comment by dirn** [comment]
I'm looking for some feedback on an implementation. I'm thinking about using a custom widget (`TwitterInput`) that will use `@` as the placeholder text for the input and will display a user's handle with the `@` (e.g., `@dirn`).  When saving the value, the `@` will be stripped (e.g., `dirn`).

I believe the latter has to happen in the form. I'll add a `validate_twitter_handle` method to `ProfileForm` to do this. If anyone knows a way to make this happen in the widget, I'd prefer to do it there.

As I'm writing this out I'm starting to think that maybe a custom field would be better.

Thoughts?

**Comment by jonafato** [comment]
Late to the discussion here, but just to summarize what's already been said elsewhere: a custom field (for transforming the submitted data) and a custom widget (for stylizing the displayed data) should be enough to accomplish this. It's best if the form itself doesn't need any extra logic, as this is wholly contained by the data in the field rather than some more complex validation that include multiple fields or other data sources.
