### ISSUE TITLE
Have more Status options for talks

### ISSUE THREAD

**Issue by logston** [PyGotham/pygotham#200]
Currently a talk can have a status of:
- draft
- submitted
- accepted 
- rejected

It would be nice if a talk could have, instead of a "accepted", a status of either "accepted - acceptance letter sent", "accepted - acceptance confirmed", or "accepted - acceptance rejected". 

Why? 

It's nice to mark a talk as excepted in a central authority like PyGohtam.org. However, since a talk can be accepted and then the speaker can reject the acceptance, we can not list the talks accepted (by flipping the "Talk List Begins" switch) until all the speakers have confirmed their acceptance or rejected their acceptance. I'd like to be able to mark a talk as accepted and only once a talk is marked as "accepted - acceptance confirmed" does it show up in the Talk List.

**Comment by dirn** [comment]
This will be quite the undertaking assigned  code will need to check for strings like `'accepted - acceptance confirmed'` or, once status is moved to a model rather than an enumeration, the status table will need a field to designate which status options relate to which site status (e.g., shows as accepted on the dashboard, shows on the talk list, etc.).

I'm definitely in favor of the latter.

**Comment by dirn** [comment]
We'll probably implement this using a [hybrid attribute](http://docs.sqlalchemy.org/en/rel_1_0/orm/extensions/hybrid.html).
